spring.application.name=worksphere
spring.datasource.url=jdbc:postgresql://localhost:5432/worksphere
spring.datasource.username=postgres
spring.datasource.password=raj

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=worksphere-secret-key-for-jwt-2026-secure